### ISSUE TITLE
Add signal strength for each tuner?

### ISSUE THREAD

**Issue by DuelCoreF18** [uvjim/hass_hdhomerun#100]
Would it be possible to add signal strength details for each tuner if the tuner was not idle? Trying to track down why a specific OTA stations is cutting out at night. Tuned in vs idle will definitely help, but it would be really interesting to see a logged history of the signal strength leading up to when it fails.

My best guess right now is a close neighbor might have an LED that's messing up VHF signal, but the more data I have the easier it would be to track down the root cause.

Thanks.

**Comment by uvjim** [comment]
Thanks for bringing this up.  Could you confirm that the signal strength attribute on the tuner is what you're after?  If so, you could handle this in a template sensor in the interim - not the best solution, I get that.  However, I have some work to do re: entity naming etc which I think should be done to make this easier.

**Comment by uvjim** [comment]
OK. The same holds true. Signal quality is an attribute in the tuner that you could template out to a sensor.

I have a decision to make really... Treat each tuner as a device and attach entities to it. Or, keep them all under the single device as they are now and name each entity per the tuner.

With either of those I still need to do the entity naming work previously mentioned.

**Comment by uvjim** [comment]
RE: becoming official... The code possibly isn't in a state that it would be allowed in. The `pyhdhr` library isn't published separately (although I could do that). I don't really have the time to get it into shape.

Also, if I go that route then any fixes etc will have to follow the HASS release schedule. Horses for courses really.

**Comment by DuelCoreF18** [comment]
Would one of those options be more favorable with different hdhomerun devices having different numbers of Tuners? 2, 3, 4, & 16 are all the current tuner count options I believe.

Would one of those options be better in the event of multiple devices? I run 2x Flex 4k with 4 Tuners each for example. One for each antenna on the roof. 

Just trying to help you brainstorm edge cases if it helps make one solution better than the other. Software Engineer, but haven't gotten under the hood of HA.

Official: I get that... It's a time sink. Love what you have started. Keep up the great work.

**Comment by uvjim** [comment]
Keep your eyes open for an upcoming beta. I have a bit more testing to do, but I have a branch working locally that has split tuners to devices with separate entities for each of the current extra attributes.

**Comment by uvjim** [comment]
Hopefully this is addressed in #103.  I have released as a beta in `2024.5.1b0`.  Could you test and let me know if I've broken anything please?

**Comment by AnthonyBe** [comment]
Updated to 2024.5.1b0 - looks good so far!
My hardware is HDHomeRun CONNECT QUATRO (Model: HDHR5-4DT)

![msedge_2024-05-26_12-25-37](https://github.com/uvjim/hass_hdhomerun/assets/17214552/b7c320f8-1426-4f7a-a9ce-9e653ca5445e)

**Comment by Fratopolis** [comment]
I'm stupid excited for this addition

**Comment by dioneimiodutzki** [comment]
working well for me too, thanks a lot!

**Comment by uvjim** [comment]
Released now in `2024.5.1`
