### ISSUE TITLE
Where to install from?

### ISSUE THREAD

**Issue by AnthonyBe** [uvjim/hass_hdhomerun#81]
Sorry, a stupid question, but I've just found this repo after troubleshooting my way through @burnnat's HDHomeRun HACS integration which appears to be abandoned.

Where/How do you install this integration? As I don't see it included in the OOB HA integrations, nor in HACS? Or is this a manual install?

I'm currently using

- Home Assistant 2022.12.8
- Supervisor 2022.12.1
- Operating System 9.4

**Comment by uvjim** [comment]
You'll need to add the repository to the `Custom Repositories` list in HACS.

**Comment by AnthonyBe** [comment]
Thanks for confirming and thanks for the integration!

**Comment by uvjim** [comment]
No problem. Enjoy.
